"""descrição_da_migracao

Revision ID: 9ba1a942e52f
Revises: 
Create Date: 2023-07-15 16:46:26.110507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba1a942e52f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Biblioteca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=False),
    sa.Column('resumo', sa.String(length=400), nullable=False),
    sa.Column('saiba_mais', sa.String(length=255), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DisplayCast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('capa', sa.String(length=255), nullable=False),
    sa.Column('link_iframe', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('capa', sa.String(length=255), nullable=False),
    sa.Column('pagina', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resumo', sa.String(length=255), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Projeto_DisplayCast',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('displaycast_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('projeto_id', 'displaycast_id')
    )
    op.create_table('Projeto_Games',
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('projeto_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Projeto_Games')
    op.drop_table('Projeto_DisplayCast')
    op.drop_table('Projeto')
    op.drop_table('Games')
    op.drop_table('DisplayCast')
    op.drop_table('Colaboradores')
    op.drop_table('Cargo')
    op.drop_table('Biblioteca')
    # ### end Alembic commands ###
